import embedded from '@/data/equivalences.json';
import type { OffProduct } from '@/lib/off';

/**
 * `equivalences.json`: `version` (generation date), `manual` (generic equivalences written by
 * hand, schema owned by the equivalences repository) and `auto` (popular milk-free products,
 * keyed by Open Food Facts category tag, generated by the weekly script).
 */
export interface EquivalencesFile {
  version: string;
  manual: unknown[];
  auto: Record<string, OffProduct[]>;
}

const EMPTY: EquivalencesFile = { version: '', manual: [], auto: {} };

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isProduct(value: unknown): value is OffProduct {
  return isObject(value) && typeof value.code === 'string' && value.code.length > 0;
}

/** The file when its three parts have the expected shape, `null` otherwise. */
export function parseEquivalences(raw: unknown): EquivalencesFile | null {
  if (!isObject(raw)) return null;
  const { version, manual, auto } = raw;
  if (typeof version !== 'string' || !Array.isArray(manual) || !isObject(auto)) return null;
  const categories = Object.values(auto);
  if (!categories.every((products) => Array.isArray(products) && products.every(isProduct))) {
    return null;
  }
  return { version, manual, auto: auto as Record<string, OffProduct[]> };
}

/** Copy shipped with the app, used until a downloaded version exists. */
export const EMBEDDED_EQUIVALENCES: EquivalencesFile = parseEquivalences(embedded) ?? EMPTY;

/** `auto` products of each category, in the order of the tags given. */
export function equivalenceProducts(
  file: EquivalencesFile,
  categoryTags: readonly (string | null | undefined)[]
): OffProduct[] {
  return categoryTags.flatMap((tag) => (tag ? (file.auto[tag] ?? []) : []));
}
